package sv.com.model;
// Generated 04.02.2018 20:26:54 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Idioma generated by hbm2java
 */
public class Idioma implements java.io.Serializable {

	private Integer idIdioma;
	private String idioma;
	private Set<Libro> libros = new HashSet<Libro>(0);

	public Idioma() {
	}

	public Idioma(String idioma) {
		this.idioma = idioma;
	}

	public Idioma(String idioma, Set<Libro> libros) {
		this.idioma = idioma;
		this.libros = libros;
	}

	public Integer getIdIdioma() {
		return this.idIdioma;
	}

	public void setIdIdioma(Integer idIdioma) {
		this.idIdioma = idIdioma;
	}

	public String getIdioma() {
		return this.idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}

	public Set<Libro> getLibros() {
		return this.libros;
	}

	public void setLibros(Set<Libro> libros) {
		this.libros = libros;
	}

}
